# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/newbrain',
                'doc_host': 'https://hartphoenix.github.io',
                'git_url': 'https://github.com/hartphoenix/newbrain',
                'lib_path': 'newbrain'},
  'syms': {'newbrain.core': {'newbrain.core.foo': ('core.html#foo', 'newbrain/core.py')}}}
